### ISSUE TITLE
todo list for migration from kdyby/translation

### ISSUE THREAD

**Issue by Ivorius** [contributte/translation#1]
It would be nice to have got the todo list for migration

**Comment by aleswita** [comment]
What I known, only extension settings are changed and this you can find in docs.

**Comment by spaze** [comment]
Can confirm, migrated from kdyby/translation to contributte/translation a few days ago and 

Extension config:
```diff
 extensions:
-	translation: Kdyby\Translation\DI\TranslationExtension
+	translation: Contributte\Translation\DI\TranslationExtension
```

Namespace imports (or type declarations in case of no namespace import):
```diff
- use \Kdyby\Translation\Translator;
+ use \Contributte\Translation\Translator;
```

Configuration (I don't use any locale resolvers, locale is "resolved" by specifying a default locale in a config file loaded for each domain, there's a different domain for each language version)
```diff
translation:
-	default: cs_CZ
-	whitelist: [cs, en]
-	resolvers:
-		header: off
-		request: off
-		session: off
+	locales:
+		default: cs_CZ
+		whitelist: [cs, en]
+	localeResolvers!: []
+	dirs:
+		- %appDir%/lang
```

Plus I went through an upgrade to Nette 3 but that's a different story. Thanks for creating this package!
