### ISSUE TITLE
Not working parameters in untranslated message

### ISSUE THREAD

**Issue by martenb** [contributte/translation#104]
Test created #103

**Comment by aleswita** [comment]
You trying translate key `Hi %name%!`, but this key not contain in any neon file.. so what you think will be returned?

**Comment by aleswita** [comment]
Correct key is `messages.hi` or only `hi`, look https://github.com/contributte/translation/blob/master/tests/Tests/TranslatorTest.phpt#L115

**Comment by martenb** [comment]
Expected result is in test. It works that way before.

Dne pá 24. 6. 2022 7:27 uživatel Aleš ***@***.***> napsal:

**Comment by aleswita** [comment]
Hmm, you are right, but no idea how to fix it.

**Comment by martenb** [comment]
ok, it looks, that returnOriginalMessage: false fixed issue for me..
