### ISSUE TITLE
Latte 3 support

### ISSUE THREAD

**Issue by MartinMystikJonas** [contributte/translation#105]
Current version does not support Latte 3.

Is there any work in progress on Latte support already? If not should I try to prepare PR with it?

**Comment by MartinMystikJonas** [comment]
@aleswita I started working on PR with Latte 3 support. I have a bit struggle with new Latte 3 macros/tags but I hope I will solve it soon.

**Comment by aleswita** [comment]
@MartinMystikJonas sorry for late answer, but I was on hollyday.. thanks for starting works on it..

**Comment by MartinMystikJonas** [comment]
PR is ready #106
