### ISSUE TITLE
Possibility to change format of translation key

### ISSUE THREAD

**Issue by zeleznypa** [contributte/translation#107]
Will it be possible please to use a separate function to assemble translation key?

https://github.com/contributte/translation/blob/d24a58184356a8b38e524826c62431d7f2f27cd4/src/Translator.php#L322

Currently the translation key have format `%key%`, but for example [Laravel](https://laravel.com/docs/9.x/localization#replacing-parameters-in-translation-strings) use the format `:key`. 

When the DevStack consist some parts, that expect different format, it will be useful to have possibility to unify the format across the project.

To solve this now I have to overload whole `translate` function with all other logic.

**Comment by aleswita** [comment]
any idea how to implement?

**Comment by zeleznypa** [comment]
@aleswita From my point of view, the simplest way is to encapsulate this line into method, that can be overwritten.

Another and maybe better way is to have this method registered as a callback in the Translator object property...
