### ISSUE TITLE
Nette/Utils 4.0.0 dependency

### ISSUE THREAD

**Issue by zeleznypa** [contributte/translation#115]
The current version of the package blocks upgrading to the latest version of [Nette/Utils](https://packagist.org/packages/nette/utils#v4.0.0).

**Comment by dakur** [comment]
And/or `nette/finder` as well which is related.

**Comment by zeleznypa** [comment]
Was fixed in https://github.com/contributte/translation/pull/116

**Comment by dakur** [comment]
Thanks!
