### ISSUE TITLE
Locale cannot be changed during request?

### ISSUE THREAD

**Issue by josefsabl** [contributte/translation#117]
Hello, I have a CLI script that sends e-mails to users. Each user obviously can have a different preferred locale.

I am using the `$localeResolver->setLocale()` trick.

But each e-mail sent is translated according to the first e-mails locale of the batch.

I tried to debug a little and it looks like although i call `setLocale` many times, the resolve function is called only once.

I cannot workaround the problem by calling `trans` with optional locale argument. I need the translation to work in latte.

**Comment by josefsabl** [comment]
This is my "hack"

```php
assert($translator instanceof \Symfony\Component\Translation\Translator);
$translator->setLocale($command->lang);
```

**Comment by aleswita** [comment]
I think better solution in command emails is passing language as parameter

{_token, null, [], null, 'en'}
