### ISSUE TITLE
how to use it on forms

### ISSUE THREAD

**Issue by alnux** [contributte/translation#121]
hi there is no information of how to use on forms by example i have this

locale.en.neon
```
email_username: "Email / Username"
please_enter_yout_username: "Please enter your username"
remember_me: "Remember me"
```

form
```
/** @var Nette\Localization\Translator @inject */
	public $translator;

protected function create()
	{
		$form = new Form;
		$form->setTranslator($this->translator);
               $form->addCheckbox('remember', 'locale.remember_me') // <-- the translate key
		return $form;
	}

```

on nette form translate says that if i put setTranslator it will auto put the translate parts [refer](https://doc.nette.org/en/forms/rendering#toc-translating) but when it render just print the key, but i cant make that this works with checkbox

**Comment by darkWolf-PR** [comment]
Hi, I think u are injecting wrong service. U shoudl have this - Contributte\Translation\Translator;

For example, my shortened code from form in component, mostly, the only difference is Translator added by constructor instead of @inject :

```
use Contributte\Translation\Translator;


class ThisForm extends UI\Control
{
    private Translator $translator;

    public function __construct(Translator $translator) {
        $this->translator = $translator;
    }
    
    protected function createComponentForm()
    {
        $form = new Form;
        $form->setTranslator($this->translator);
        $form->addText('name', 'front.form.name');
        ...
    }
}
```
