### ISSUE TITLE
Globalni volani _t(...)

### ISSUE THREAD

**Issue by JStika** [contributte/translation#133]
Musel jsem upgradovat kody na php 8.3 a prisel jsem o pohodu pouziti https://github.com/h4kuna/gettext-latte.
Ted pouzivam Vase https://github.com/contributte/translation (data z db). V latte funguje bez problemu. 
Ale uz to nelze pouzit ve formularich [BaseForm], presenterch [BasePresnter], modelech [BaseMode], componentach [BaseControl].

Potreboval bych nejakou uplne globalni funkci treba jako t(...), kterou bych mohl nahradit volani _(...). 

if (!function_exists('App\Core\Services\Translator\_t')) {
	/**
	 * @param string $message
	 * @param array|null $parameters
	 * @param string|null $locale
	 * @return string
	 */
	function _t(string $message, ?array $parameters = [], ?string $locale = 'cs') : string
	{
		static $translator = null;
		if ($translator === null) {
			//$translator = new \Contributte\Translation\Translator(??????);
		}

		return $translator->translate($message, $parameters, $locale);
	}
}

Ale nevim jak to napsat, aktivovat. Muzete mi, prosim, poradit, jak by mohl kod vypadat (extension ?)? Pozadam Vas o radu jak na to.

Dekuji

**Comment by spaze** [comment]
Lze to použít i v controllerech a dalších, stačí si translator nechat předat z dependency injection containeru, v presenteru např. jako

```php
use Contributte\Translation\Translator;

class ContactPresenter extends BasePresenter
{

	public function __construct(
		private readonly Translator $translator,
	) {
		parent::__construct();
	}
...
```

ve fomulářích (resp. v továrních třídách) i jinde obdobně:

```php
readonly class PostFormFactory
{

	public function __construct(
		private FormFactory $factory,
		private Translator $translator,
...
```

a poté si nechat přeložit něco:

```php
$this->translator->translate('messages.title.contact');
```

**Comment by JStika** [comment]
Dekuji za odpoved. 
Tak, jak jste psal, to mam nyni, to neni problem. 
Chtel bych to volat jako nejakou uplne globalni funkci treba jako t(...), zel, nevim jak to napsat, aktivovat. S tim potrebuji poradit.

**Comment by spaze** [comment]
Aha, špatně jsem pochopil "Ale uz to nelze pouzit", pardon. Určitě by šlo funkci definovat a načíst v bootstrapu aplikace, v té funkci nějakou statickou metodou získat DI container a z DI containeru pak získat službu `Contributte\Translation\Translator` a na ní pak zavolat metodu `translate`.

Spíš bych to tak ale nedělal, je to skrytá závislost na okolním kódu, a používal to standardně jak jsem ukazoval a jak to už to máte. Když něco potřebuje translator, tak si má o něj požádat a má ho to dostat z DI containeru.

**Comment by JStika** [comment]
Dekuji za odpoved. Mate urcite pravdu. 
Ale narazil jsem na problem pri pouziti u Form-u: treba u select-u naplnenych se jmeny uzivatelu, nebo roku. Vim o ->setTranslator(null), jenze tato methoda vypne preklad upne, na dalsi pvky se veprdne.

Proto chci nejakou implementaci pro globalni func i t(...), abych mel preklad pod vlastni kontrolou.
Jen nevim jak.

**Comment by aleswita** [comment]
translator obsahuje i tzv wrappery, kterymi jde obalit text, ktery nechcete prekladat
https://github.com/contributte/translation/tree/master/.docs#wrappers

btw mozna by vam vyhovovala v ramci Nette i takova moznost, kde si v base presenteru udelate public metodu na preklad a k te se pak jednoduse dostane vsude, od presenteru, po tovarny..

**Comment by JStika** [comment]
Nasel jsem toto zajimave reseni https://github.com/orisai/translation-contracts.
Ale nedokazu to "naroubovat'' na vas translator.

**Comment by spaze** [comment]
Když se `setTranslator(null)` zavolá jen na konkrétním prvků, mělo by to přestat překládat jen ten prvek, ne žádné jiné, viz [dokumentace](https://doc.nette.org/cs/forms/rendering#toc-prekladani)

Vytvoření globální funkce samo o sobě nezabrání překládání formulářových prvků, to Vám nepomůže. Můžete ji klidně vytvořit jak jsem naznačil, což je podobné tomu řešení v orisai, ale to záleží jak se aplikace startuje apod. Ale stejně to nepomůže :-) Použil bych co psal Aleš výše, nebo `setTranslator(null)` na konkrétním prvku.
