### ISSUE TITLE
It is not compatible with symfony/translation >=5.0.0

### ISSUE THREAD

**Issue by RiKap** [contributte/translation#20]
Hey it is not comaptible with symfony/translation >=5.0.0.
![image](https://user-images.githubusercontent.com/6736715/74019657-48980380-4998-11ea-8cea-0f1bd52978ea.png)

Same problem is in `DatabaseAbstract`.

I see two solutions:
- Drop support for symfony/translation < 5.0.0
- Remove symfony/translation >=5.0.0 from supported version

**Comment by mabar** [comment]
#18 duplicate

**Comment by RiKap** [comment]
Sorry I see. My frontend collegue had php 7.3 in console, but localhost server used 7.1 and I did not noticed that. :)
