### ISSUE TITLE
setLocalesWhitelist

### ISSUE THREAD

**Issue by mareksloser** [contributte/translation#23]
Hello, where are settings for setLocalesWhitelist? I Session doesnt return locale value.

**Comment by aleswita** [comment]
https://github.com/contributte/translation/blob/master/.docs/README.md#configuration
```yaml
translation:
    locales:
        whitelist: [en, cs, sk]

**Comment by mareksloser** [comment]
Thank you, i have same in neon but this function return every time null

`if (!in_array(Nette\Utils\Strings::substring($this->sessionSection[self::$parameter], 0, 2), array_map(function ($locale): string {
			return Nette\Utils\Strings::substring($locale, 0, 2);
		}, $translator->availableLocales), true)) {
			return null;
		}`

**Comment by aleswita** [comment]
And return null on row 45: https://github.com/contributte/translation/blob/master/src/LocalesResolvers/Session.php#L45

or row 52?
https://github.com/contributte/translation/blob/master/src/LocalesResolvers/Session.php#L52

**Comment by mareksloser** [comment]
52

**Comment by aleswita** [comment]
So pls paste your neon configuration and code sample, how you handle with locale in presenter

**Comment by mareksloser** [comment]
`translation:
    locales:
        whitelist: [cs, en]
        default: cs
        fallback: [cs]
    dirs:
        - %appDir%/lang`

**Comment by mareksloser** [comment]
`    /** @var Nette\Localization\ITranslator @inject */
    public $translator;

    /** @var Contributte\Translation\LocalesResolvers\Session @inject */
    public $translatorSessionResolver;


    public function handleChangeLocale(string $locale): void
    {
        $this->translatorSessionResolver->setLocale($locale);
        $this->flashMessage('Jazyk byl upraven na: '.$locale);
        //$this->redirect('this');
    }`

**Comment by aleswita** [comment]
Have you correct files in %appDir%/lang ?

Code bellow works for me:

```yaml
translation:
	locales:
		default: 'cs'
		whitelist: [cs, en]
		fallback: cs
	localeResolvers:
		- Contributte\Translation\LocalesResolvers\Session
	dirs:
		- %appDir%/lang
```

```php
abstract class BasePresenter extends Nette\Application\UI\Presenter
{

	/** @var Nette\Localization\ITranslator @inject */
	public $translator;

	/** @var \Contributte\Translation\LocalesResolvers\Session @inject */
	public $translatorSessionResolver;

	/** @var \Contributte\Translation\LocaleResolver @inject */
	public $translatorLocaleResolver;

	public function beforeRender()
	{
		parent::beforeRender();

		$this->translatorSessionResolver->setLocale('sk');

		bdump($this->translatorSessionResolver->resolve($this->translator));// print 'sk'
	}

}

**Comment by mareksloser** [comment]
Folder lang is empty atm. (but when i use router - its working well)

https://masaze.hbwh.cz/

Your code print null for me.

**Comment by mareksloser** [comment]
https://masaze.hbwh.cz/en

https://masaze.hbwh.cz/cs

**Comment by aleswita** [comment]
So its because Session resolver have whitelist check, others resolvers no.. its good point why missing :-)

**Comment by aleswita** [comment]
@mareksloser can you check dev-master if OK?

**Comment by mareksloser** [comment]
Contact me info@mareksloser.cz it will be faster, then this comunication .)

**Comment by mareksloser** [comment]
`public function beforeRender()
	{
		parent::beforeRender();

		$this->translatorSessionResolver->setLocale('cs');

		bdump($this->translatorSessionResolver->resolve($this->translator));// print 'cs'
	}`

this code is working, handler not, but i will find it .))

**Comment by aleswita** [comment]
Muzem psat cesky v mejlech..

To co jsem opravil, byl nejaky stary relic kodu, co tam nemel co delat,
tedka ti session resolver vytahne jakykoliv ulozeny jazyk a az
localeresolver ho zvaliduje podle whitelistu.. co mas tedka za proble?


Dne po 23. 3. 2020 18:37 uživatel Marek Šloser <notifications@github.com>
napsal:

**Comment by mareksloser** [comment]
Už asi nic, ten handler nefungoval protože tam byl ten tvůj kód který to vždy přepsal. Vše ok

Teď řešim proč se to chová jinak na localu než na produkci, ale to bude nastavením dockeru.

Ale jinak děkuji za help

**Comment by aleswita** [comment]
Ja diky za odhaleni skryte chyby ;-)

Dne po 23. 3. 2020 18:51 uživatel Marek Šloser <notifications@github.com>
napsal:
