### ISSUE TITLE
DB - untranslated text

### ISSUE THREAD

**Issue by mareksloser** [contributte/translation#24]
Hello, can you help me? 
Doctrine 2 loading

I would like use this: When translator detect untranslated text, the code automaticaly create new db insert locale: message: "key.from.translate." and i can create easy code to find untranslated text in DB and translate it

And question - Where i cant catch unstranslated text?

**Comment by aleswita** [comment]
So you can create logger and enabled in translator and translator will be sent to logger all untranslated messages.

https://github.com/contributte/translation/blob/master/src/DI/TranslationExtension.php#L28
