### ISSUE TITLE
Translation of text with spaces is taken from messages.local.neon

### ISSUE THREAD

**Issue by TomasHalasz** [contributte/translation#26]
I've issue with translation of text with spaces. For example `$translator->translate('Kočka leze dírou, pes oknem');`  is looking for string "Kočka leze dírou, pes oknem" in default messages.local.neon even if I hade set different domain by `$translator->setPrefix(['customModule.status']); `  I don't know if it is error or behavior by design. 

My idea is to replace spaces with underscores in messages, because it's still readable in case of missing translate in neon. 
And the best way in my opinion is in Translator.php :

```
public function translate($message, ...$parameters): string // @comment

{

        $message = str_ireplace(" ","_",$message);


```

Nice would be if user can set on or off this replacing space by underscore. What do you think?

**Comment by aleswita** [comment]
If message contain dot and space, translator use message domain by default. Its expected behaviour.
https://github.com/contributte/translation/blob/master/src/Helpers.php#L26

Try this:
$translator->translate('My message with spaces.', null, [], 'my_domain');

**Comment by TomasHalasz** [comment]
Thanks but it doesn't help. Tracy said that this translation is missing:
```
ID: applicationModule.invoice.Forma úhrady: 
Domain: messages
Count:  1
```

It's in form:

```
    protected function createComponentEdit($name)
    {	
        $form = new Form($this, $name);
        $form->setTranslator($this->translator);
        $this->translator->setPrefix(['applicationModule.invoice']);
        $arrPay = $this->PaymentTypesManager->findAll()->order('name')->fetchPairs('id','name');
        $form->addSelect('cl_payment_types_id',$this->translator->translate('Forma úhrady:'),$arrPay)
            ->setTranslator(NULL)
            ->setHtmlAttribute('class','form-control chzn-select input-sm');

```
And lang file is applicationModule.cs_CZ.neon:
```
invoice:
	EditDocNum: "upravit číslo dokladu"
	Forma úhrady:: "Forma úhrady:"
```

Result of this in html is:  `applicationModule.invoice.applicationModule.invoice.Forma úhrady:`
The same result I get if I remove:  `$this->translator->setPrefix(['applicationModule.invoice']); `
and use in form:  `$form->addSelect('cl_payment_types_id',$this->translator->translate('Forma úhrady:', null, [], 'applicationModule.invoice'),$arrPay)`

So I don't realy know why is my translation domain ignored....

**Comment by aleswita** [comment]
Code bellow works for me:

```php
$translator->setPrefix(['a']);
var_dump($translator->translate('Ahoj jak se mas:', [], 'my_domain'));
```

```yaml
a:
	Ahoj jak se mas:: "hmm"

**Comment by TomasHalasz** [comment]
Ok, and in your example, neon file with translation has name messages.cs_CZ.neon? If yes, it works and its correct. But in my case I need to have translation file named according to domain name. 

In next example is translator still looking for translation into messages.cs_CZ.neon:

```
$translator->setPrefix(['applicationModule.invoice']);
var_dump($translator->translate('Forma úhrady:'));

```
applicationModule.cs_CZ.neon:
```
invoice:
	Forma úhrady:: "Forma úhrady:"
```

And I think that reason is in Helpers.php:
```
public static function extractMessage(string $message): array
	{
		if (strpos($message, '.') !== false && strpos($message, ' ') === false) {
			[$domain, $message] = explode('.', $message, 2);

		} else {
			$domain = 'messages';
		}

		return [$domain, $message];
	}
```
Reason is directly in first line with condition. Because exploding string by '.' is done only if $messsage don't contain space. 

`strpos($message, ' ') === false`

And in my message is space, so domain is automaticly given 
```
		} else {
			$domain = 'messages';
		}
```
Is there some reason to have this part of condition ? 
`strpos($message, ' ') === false`

Wouldn't be better only this ?
```
        if (strpos($message, '.') !== false ) {		    
			[$domain, $message] = explode('.', $message, 2);
		} else {
			$domain = 'messages';
		}
```

Thanks for your help! :-)

**Comment by aleswita** [comment]
My code works for every domain name, look on third parameter. If you set domain in parameter, extract message will be skip -> this is solution for you.

But no idea why **strpos($message, ' ') === false** is used. You can try send PR with solution without BC breaks.

**Comment by TomasHalasz** [comment]
ok I will send PR. Thanks

**Comment by aleswita** [comment]
@TomasHalasz can you try "space" branch?
