### ISSUE TITLE
Fallback locales list always contains extension default value

### ISSUE THREAD

**Issue by rozsival** [contributte/translation#31]
As of `v0.7.0` the DI extension defines `['en_US']` as a default value for `translation.locales.fallback`.

Due to [this issue / behavior](https://github.com/nette/schema/issues/13) of `nette/schema`, the default value is **always** present in the configured list of fallback locales. This is unwanted behavior as applications without `en_US` locale should never have it as a fallback. 

Maybe fe0fae71e9faac1f2ed45e7ea35875726f806574 could be reverted to the previous implementation?

**Comment by aleswita** [comment]
Thank you for report, this is realy unexpected.. fixed in 0.7.1
