### ISSUE TITLE
Nelze volat DI Translator

### ISSUE THREAD

**Issue by kickz** [contributte/translation#4]
Chtěl bych se zeptat, proč nejde volat třída Translator globálně stejně jako u Kdyby viz chyba ? 

 Service of type Contributte\Translation\Translator needed by $translator in __construct() not found. Did you register it in configuration file?

Neměla by být dostupná po zavolání rozšíření v config.neon ?

Druhá věc je, že tu vůbec není v dokumentaci vysvětleno, jak si třeba udělat rozšíření přímo na DB nikoliv podle souboru, což díky Translatoru v Kdyby bylo možné.

Díky

**Comment by aleswita** [comment]
1. Musis injectovat/predavat v konstruktoru **Nette\Localization\ITranslator**
2. Pokud chces slozitejsi DB drivery (treba aby se invalidovala cache pri zmene), musis si napsat vlastni implementaci ConfigCacheFactory. Ale pokud mas nejaky interface, kde si zapisujes/upravujes preklady, staci pri ulozeni dat preulozit ilzaroven soubor s nastavenim a cache se invaliduje

**Comment by kickz** [comment]
To sice ano, ale kde máš funkci, která např. odchytne všechny ty stávající překlady ? 
V ITranslator máš jen funkci translate, ale třeba getCatalogue na získání překladů ne, takže tím bych obešel zbytečeně tvůj Translator ne ?

**Comment by aleswita** [comment]
trida **Contribute\Translation\Translator** je v DI nastavena jako **Nette\Localization\ITranslator**, tzn ze pokud budes injectovat Nette\Localization\ITranslator, DI ti vlozi *Contribute\Translation\Translator

**Comment by mabar** [comment]
Jde o to, aby se využíval obecný interface namísto konkrétní implementace -> služby jsou vyměnitelné. Kdybys chtěl někde jiný translator, nedědící z Contributte/Translation, tak ti bude stačit změnit konfiguraci, ne kód.
Nově se zkrátka zakazuje, aby šlo automaticky injectovat konkrétní implementaci. Namísto toho má konkrétní implementace povolený auto-inject na základě rozhraní.
