### ISSUE TITLE
Chybějící překlady

### ISSUE THREAD

**Issue by kickz** [contributte/translation#6]
Chci se zeptat, jak by jste optimálně řešili vytažení chybějících překladů, nyní by asi nebyl problém např. udělat funkci v translatoru, která by dávala chybějící překlady do tracy panelu + někam do pole v té třídě a následně to nějak vytáhnout nebo by jste měli jiné řešení ? 

Díky

**Comment by aleswita** [comment]
Currently no way, how to logging missing translation... you can try send the PR.

**Comment by aleswita** [comment]
https://github.com/contributte/translation/commit/cca920e06b9c776dfd703967b3d59776af35fb38
