### ISSUE TITLE
How to disable translate not existing translations?

### ISSUE THREAD

**Issue by matak** [contributte/translation#66]
For example 

$form->addSelect("email", $emails)

obviously there is no emails translations, but translator automatically expect that info@example is domain and cz is message, so finally is rendered only CZ word.

Thats very strange behaviour, how to disable it? I know that you can use NoTranslate element, but it is impossible to fix all these places.

**Comment by aleswita** [comment]
In version 0.9.0. was added option returnOriginalMessage
https://github.com/contributte/translation/blob/master/src/DI/TranslationExtension.php#L81
Second choice is use NotTranslate wrapper, look into the docs.

**Comment by matak** [comment]
I believe that solution is configuration

returnOriginalMessage which is not part of documentation

**Comment by matak** [comment]
> In version 0.9.0. was added option returnOriginalMessage
> https://github.com/contributte/translation/blob/master/src/DI/TranslationExtension.php#L81
> Second choice is use NotTranslate wrapper, look into the docs.

thanks, answer at the same time, yes this is solution, but pls add in doc?

**Comment by aleswita** [comment]
You can add by PR

**Comment by matak** [comment]
#67
