### ISSUE TITLE
BC breaks in the 0.9 branch

### ISSUE THREAD

**Issue by jaroslavlibal** [contributte/translation#69]
After upgrading to the 0.9 branch, strange things started happening.

We used the following notation:
```latte
{foreach $messages as $message}
    <div class="alert alert-{$message->getType()->getValue()}">
        {_$message->getContent()}
    </div>
{/foreach}
```

Where `$message` is an object with the `getContent()` method returning `string|Contributte\Translation\Wrappers\Message`.

Since version 0.9 I started to get an error
`Call to a member function getContent() on string`
at `echo LR\Filters::escapeHtmlText(call_user_func($this->filters->translate, $message . $message->getContent()));`

The problem is that my `$message` variable is overwritten by the extension's internal code using the same variable name.

If I rename the variable, e.g. to `$messageA`, a related problem occurs.

`Object of class Contributte\Translation\Wrappers\Message could not be converted to string` at
`echo LR\Filters::escapeHtmlText(call_user_func($this->filters->translate, $message . $messageA->getContent()));`

In this case (I believe, but it may not be true) the newly added concat with the `$message` variable is to blame since `Contributte\Translation\Wrappers\Message` does not have a `__toString` magic method. Or does it mean that now it is not possible to use `Contributte\Translation\Wrappers\Message` objects in latte macros?

if I downgrade the library to the 0.8.3 version the everything works fine.

**Comment by aleswita** [comment]
Can you try dev-master?

**Comment by jaroslavlibal** [comment]
I'm still getting an error
```
Object of class Contributte\Translation\Wrappers\Message could not be converted to string
echo LR\Filters::escapeHtmlText(
    call_user_func($this->filters->translate, $ʟ_contributteTranslationMessage . $message->getContent())
);
```

**Comment by aleswita** [comment]
and now?

**Comment by jaroslavlibal** [comment]
Now everything seems to be working as before. Thank you!
