### ISSUE TITLE
PrefixedTranslator not working in forms after update to 0.9.x

### ISSUE THREAD

**Issue by zraly** [contributte/translation#75]
When I updated to version 0.9.x, translations stopped being translated in forms with `PrefixedTranslator`.

The translation is in NEON file called `admin.cs_CZ.neon` and the form in latte is located inside `{translator admin.domain}` tag.

`admin.cs_CZ.neon`:

```
domain:
   myForm:
      sub: "Odeslat"
```

Form translator is defined this way:

```
$form->setTranslator($this->translator->createPrefixedTranslator('myForm'));
```

Works in 0.8.x. In 0.9.x it prints only the key `sub`.

**Comment by aleswita** [comment]
Can you try ` init_lang` branch?

**Comment by zraly** [comment]
Tried, doesn't work :( Still the same.

**Comment by zraly** [comment]
Actually, my composer updated to `init_lang` branch, but I can't find it here. Am I doing something wrong?

**Comment by zraly** [comment]
I am not sure if I am able to do this. But this is weird: If I set the prefixed translator to a form like this:

`$form->setTranslator($this->translator->createPrefixedTranslator('volnaDomenaForm'));`

It thinks, that `volnaDomenaForm` is the domain:

<img width="679" alt="Snímek obrazovky 2021-08-12 v 12 19 15" src="https://user-images.githubusercontent.com/522848/129180780-0de78001-4b4f-4469-aaab-18f4d9984149.png">

Any thoughts?

**Comment by slischka** [comment]
Taky mi to po aktualizaci začlo špatně překládat, ale pouze na jednom místě, kde jsem používal prefixed translator.
Tímto způsobem: `$this->translator = $translator->createPrefixedTranslator('periodicInvoices.periodicInvoicesTable');`
Vyřešil jsem jsem to tak, že jsem místo locale `cs` začal používat `cs_CZ`.
Přesněji všechny soubory jsem měl pojmenované `*.cs_CZ.neon`. Když jsem to sjednotil s překladačem tak se to rozjelo.
