### ISSUE TITLE
1.0.0 release, but tag says 0.9.4

### ISSUE THREAD

**Issue by spaze** [contributte/translation#88]
Hi,

I've noticed that [1.0.0](https://github.com/contributte/translation/releases/tag/v0.9.4) has been released, w00t!

Not sure this is intentional but it seems that it's still tagged as 0.9.4:
![chrome_2022-02-15_01-38-09](https://user-images.githubusercontent.com/1966648/153970727-a19c090e-0f54-4dbb-80d2-62fff0496943.png)
(the diff link doesn't work)

Because of the 0.9.**4** tag, composer thinks this is a patch/minor release:
![image](https://user-images.githubusercontent.com/1966648/153970892-58c9aa0a-33b0-4cc4-a015-1104e3576274.png)

If not intentional, do you think you can create a new tag and edit the release so it's using the new tag if possible?

**Comment by aleswita** [comment]
ach jo.. fixed, thank you!
