### ISSUE TITLE
getDefaultLocale() and getLocale()

### ISSUE THREAD

**Issue by BigOHenry** [contributte/translation#9]
At `Kdyby/Translator `there were these two methots - `getDefaultLocale()` and `getLocale()`. 
I am using it, but i can not figure out how to get these variables now.

Thank you!

**Comment by aleswita** [comment]
These methods Contributte/Translation also has

**getDefaultLocale()**
https://github.com/contributte/translation/blob/master/src/Translator.php#L82

**getLocale()** (inheritance from Symfony/Translation)
https://github.com/symfony/translation/blob/master/Translator.php#L158

**Comment by BigOHenry** [comment]
Thank you for reaction. 
I already tried that, but the problem was it cannot be injected it to the presenter:

```
    /**
     * @var \Contributte\Translation\Translator
     * @inject
     */
    public $translator;

public function startup() {
        parent::startup();
        $this->template->locale = $this->translator->getDefaultLocale();
    }
```
But got this error:
`Service of type Contributte\Translation\Translator used in @var annotation at App\Presenters\SignPresenter::$translator not found. Did you register it in configuration file? `

**Comment by aleswita** [comment]
You must inject always **Nette\Localization\ITranslator** and DI inject **Contributte\Translation\Translator**

Look: https://github.com/contributte/translation/issues/4#issuecomment-492972621

**Comment by BigOHenry** [comment]
Ahh, sorry for duplicate issue. 
One last question then :) Any idea what to do with phpstan? If i inject `Nette\Localization\ITranslator` and then call `getLocale()` i get error in phpstan (and in phpstorm no tipehint on this method):

**Call to an undefined method Nette\Localization\ITranslator::getLocale().**

**Comment by aleswita** [comment]
Try this:
```php
/** @var Contributte\Translation\Translator */
$translator = $this->translator;

$this->template->locale = $translator->getDefaultLocale();
```
or this:
```php
assert($this->translator instanceof Contributte\Translation\Translator);
$this->template->locale = $this->translator->getDefaultLocale();
```

**Comment by BigOHenry** [comment]
Great :) I know the first one, but dont like it but i didnt know the second one and i like it more.

Thank you very much for your time!
