### ISSUE TITLE
No loader is registered for the "array" format

### ISSUE THREAD

**Issue by Zarganwar** [contributte/translation#91]
Should extension automatically register **array** loader while inherited **neon** loader is registered? 

Same for other inherited loaders if exists.

**Comment by aleswita** [comment]
Only neon loader automatically load, look https://github.com/contributte/translation/blob/master/src/DI/TranslationExtension.php#L72

**Comment by Zarganwar** [comment]
Yes, but if you inherit something that is not abstract, you have to support that superclass as well.

**Comment by aleswita** [comment]
I do not think.
Array loader normally supported, but you must set in configuration, thats all.
