### ISSUE TITLE
Translator returns untranslated message even though the translation exists

### ISSUE THREAD

**Issue by petaak** [contributte/translation#93]
In the situation when the translation is not available in the default locale but exists in the requested locale, translator returns an untranslated message (if returnOriginalMessage=true). I think it's caused by this change https://github.com/contributte/translation/commit/e78977eb2ce0cc3104ce1fa880516521cdef228c#diff-eacdee021952408874fa89f5f706adcbc864deb46dc1b18bfb042beaad944b85R345

Shouldn't we pass the $locale parameter to the getCatalogue() call in the translation existence check to use the catalogue of the requested locale?

**Comment by aleswita** [comment]
@petaak interesting, can you test `fix` branch? -> https://github.com/contributte/translation/pull/95/files

**Comment by aleswita** [comment]
closed by https://github.com/contributte/translation/commit/9796ce36eab5561a3724ddcc8196d044cb0686d3 and https://github.com/contributte/translation/commit/b3634769f54c5092cf51d0886a5eaef12f2d686d
