### ISSUE TITLE
BUG - symfony / translation set default locale

### ISSUE THREAD

**Issue by borisjanata** [contributte/translation#94]
The problem is that on symfony / translation they added default locale setting https://github.com/symfony/translation/commit/c1cca3eb086bb62d98890631ef6bbc65ce913dd1 . Then it defaults set locale to "en_US_POSIX" and doesn't run localeResolver vendor/contributte/translation/src/Translator.php on line 219.

**Comment by aleswita** [comment]
On my project, this happend only if no texts for translate and I think this is no problem, what you think about this?
